//go:build windows

package blocker

// defaultBlocklist is a curated set of well-known ad/tracker domains.
// Blocking a domain here also blocks all of its subdomains (see
// matchesSuffixSet in blocker_windows.go) - e.g. "doubleclick.net" also
// covers "ad.doubleclick.net".
//
// This is a solid starting point, not an exhaustive list. For broader
// coverage, drop a text file named "blocklist.txt" next to netvis.exe: one
// domain per line, blank lines and lines starting with '#' are ignored. A
// good source is StevenBlack's hosts list (github.com/StevenBlack/hosts) -
// strip the "0.0.0.0 " prefix from each line to get plain domains. If the
// default list is ever too aggressive, add exceptions to "allowlist.txt"
// next to the exe, same one-domain-per-line format.
var defaultBlocklist = []string{
	// Google ads/analytics
	"doubleclick.net",
	"googlesyndication.com",
	"googleadservices.com",
	"google-analytics.com",
	"googletagmanager.com",
	"googletagservices.com",
	"adservice.google.com",
	"admob.com",
	"admeld.com",
	"2mdn.net",
	"gstaticadssl.l.google.com",
	"pagead-inspector.appspot.com",

	// Amazon
	"amazon-adsystem.com",
	"assoc-amazon.com",

	// Ad exchanges / networks / DSPs / SSPs
	"adnxs.com",
	"adsrvr.org",
	"adform.net",
	"adroll.com",
	"criteo.com",
	"criteo.net",
	"rubiconproject.com",
	"pubmatic.com",
	"openx.net",
	"taboola.com",
	"outbrain.com",
	"media.net",
	"moatads.com",
	"scorecardresearch.com",
	"quantserve.com",
	"mopub.com",
	"applovin.com",
	"unityads.unity3d.com",
	"chartboost.com",
	"vungle.com",
	"ironsrc.com",
	"smaato.com",
	"adcolony.com",
	"inmobi.com",
	"mgid.com",
	"revcontent.com",
	"zedo.com",
	"casalemedia.com",
	"indexexchange.com",
	"sharethrough.com",
	"sovrn.com",
	"lijit.com",
	"gumgum.com",
	"yieldmo.com",
	"contextweb.com",
	"bidswitch.net",
	"advertising.com",
	"atdmt.com",
	"tribalfusion.com",
	"exoclick.com",
	"propellerads.com",
	"popads.net",
	"juicyads.com",
	"trafficjunky.net",
	"plugrush.com",
	"adcash.com",
	"bidvertiser.com",
	"infolinks.com",
	"adsterra.com",
	"hilltopads.net",
	"admaven.com",
	"connatix.com",
	"teads.tv",
	"spotxchange.com",
	"spotx.tv",
	"freewheel.tv",
	"tremorhub.com",
	"telaria.com",
	"springserve.com",
	"smartadserver.com",
	"adition.com",
	"improvedigital.com",
	"triplelift.com",
	"districtm.io",
	"pulsepoint.com",
	"33across.com",
	"adyoulike.com",
	"eyeota.net",
	"krxd.net",
	"lkqd.net",
	"loopme.com",
	"mediamath.com",
	"nativo.com",
	"onetag.com",
	"rlcdn.com",
	"tapad.com",
	"yieldlab.net",
	"yieldlove.com",
	"zeotap.com",
	"adsafeprotected.com",
	"doubleverify.com",
	"integral-marketing.com",
	"serving-sys.com",
	"turn.com",
	"amplitude.com",
	"branch.io",
	"appsflyer.com",
	"adjust.com",
	"kochava.com",
	"singular.net",
	"tenjin.io",

	// Social platforms' ad/analytics endpoints
	"an.facebook.com",
	"ads.facebook.com",
	"atlassolutions.com",
	"bat.bing.com",
	"ads.msn.com",
	"ads.tiktok.com",
	"analytics.tiktok.com",
	"business-api.tiktok.com",
	"ads-api.twitter.com",
	"ads-twitter.com",
	"analytics.twitter.com",
	"ads.pinterest.com",
	"ads.reddit.com",
	"ads.linkedin.com",
	"px.ads.linkedin.com",
	"adsapi.snapchat.com",
	"sc-static.net",

	// Video/CTV ad-specific
	"innovid.com",
	"extremereach.io",
	"adswizz.com",
	"triton.com",
	"streamrail.com",

	// Misc trackers commonly bundled in ad SDKs
	"mixpanel.com",
	"segment.io",
	"segment.com",
	"heapanalytics.com",
	"fullstory.com",
	"hotjar.com",
	"crazyegg.com",
	"mouseflow.com",
	"clicktale.net",
	"chartbeat.com",
	"newrelic.com",
	"nr-data.net",
}
