#include "license.h"
#include "log.h"

#include <windows.h>
#include <winhttp.h>
#include <wincrypt.h>

#include <atomic>
#include <cctype>
#include <vector>
#include <cstdlib>
#include <string>

#include <bcrypt.h>

#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "winhttp.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "crypt32.lib")

namespace license {

// The licensing server, compiled in. Deliberately not configurable at
// runtime: a settings file holding this address is a one-line license
// bypass, since anyone could point netvis at a server of their own that
// answers "licensed" to everything. Changing it means a rebuild.
//
// It is https for the same reason - redirecting the name with a hosts file
// gets you a certificate error rather than a working fake server, because
// WinHTTP validates against the Windows certificate store.
const char* const kServer = "https://netvis.cc";

// Public half of the server's answer-signing key (ECDSA P-256, X||Y hex).
// Generated by `licensing genkeys`; the private half stays on the server.
//
// This is what makes the license check independent of the network. Anyone
// with Administrator - which netvis requires - can install their own root
// certificate and redirect netvis.cc in the hosts file, at which point TLS
// proves nothing. But a fake server can't produce a signature that matches
// this key, so its "yes" is rejected all the same. Forging one means
// recovering the private key, not owning the connection.
const char* const kServerPublicKey = "e746070e7324e8594a9ca17cc1eca966947d63a2ec641787aba8bbeb3e5f"
"df54a92f65e63d32903cd7ac962382e72474f63e8588dbee765ca6781e3437319e28";
namespace {

std::wstring Widen(const std::string& s) {
    if (s.empty()) return L"";
    int n = MultiByteToWideChar(CP_UTF8, 0, s.c_str(), (int)s.size(), nullptr, 0);
    std::wstring w(n, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, s.c_str(), (int)s.size(), w.data(), n);
    return w;
}

// ---- HWID ---------------------------------------------------------------

// MachineGuid is written by Windows at install time and never changes on
// its own - the closest thing Windows has to a machine serial that any
// process can read. Explicitly 64-bit view, because a 32-bit build would
// otherwise be redirected to the WOW6432Node copy and get a different value.
std::string MachineGuid() {
    HKEY key = nullptr;
    if (RegOpenKeyExW(HKEY_LOCAL_MACHINE, L"SOFTWARE\\Microsoft\\Cryptography", 0,
                      KEY_READ | KEY_WOW64_64KEY, &key) != ERROR_SUCCESS)
        return "";
    wchar_t buf[128] = {};
    DWORD size = sizeof(buf), type = 0;
    LONG rc = RegQueryValueExW(key, L"MachineGuid", nullptr, &type, (LPBYTE)buf, &size);
    RegCloseKey(key);
    if (rc != ERROR_SUCCESS || type != REG_SZ) return "";

    char out[128] = {};
    WideCharToMultiByte(CP_UTF8, 0, buf, -1, out, sizeof(out), nullptr, nullptr);
    return out;
}

std::string SystemVolumeSerial() {
    DWORD serial = 0;
    if (!GetVolumeInformationA("C:\\", nullptr, 0, &serial, nullptr, nullptr, nullptr, 0)) return "";
    char buf[16];
    snprintf(buf, sizeof(buf), "%08lX", (unsigned long)serial);
    return buf;
}

// SHA-256, hex, truncated to 32 chars. Hashing means the raw MachineGuid
// never leaves the machine, and 128 bits is far more than enough to keep
// two customers from colliding.
std::string HashHex(const std::string& in) {
    HCRYPTPROV prov = 0;
    HCRYPTHASH hash = 0;
    std::string out;

    if (!CryptAcquireContextW(&prov, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) return out;
    if (CryptCreateHash(prov, CALG_SHA_256, 0, 0, &hash)) {
        if (CryptHashData(hash, (const BYTE*)in.data(), (DWORD)in.size(), 0)) {
            BYTE digest[32];
            DWORD len = sizeof(digest);
            if (CryptGetHashParam(hash, HP_HASHVAL, digest, &len, 0)) {
                char hex[65];
                for (DWORD i = 0; i < len; i++) snprintf(hex + i * 2, 3, "%02x", digest[i]);
                out.assign(hex, 32); // 128 bits is plenty
            }
        }
        CryptDestroyHash(hash);
    }
    CryptReleaseContext(prov, 0);
    return out;
}

// ---- signature verification ------------------------------------------

std::vector<BYTE> FromHex(const std::string& hex) {
    std::vector<BYTE> out;
    if (hex.size() % 2) return out;
    out.reserve(hex.size() / 2);
    for (size_t i = 0; i + 1 < hex.size(); i += 2) {
        auto nib = [](char c) -> int {
            if (c >= '0' && c <= '9') return c - '0';
            if (c >= 'a' && c <= 'f') return c - 'a' + 10;
            if (c >= 'A' && c <= 'F') return c - 'A' + 10;
            return -1;
        };
        int hi = nib(hex[i]), lo = nib(hex[i + 1]);
        if (hi < 0 || lo < 0) return {};
        out.push_back((BYTE)((hi << 4) | lo));
    }
    return out;
}

bool Sha256Raw(const std::string& in, BYTE out[32]) {
    HCRYPTPROV prov = 0;
    HCRYPTHASH hash = 0;
    bool ok = false;
    if (!CryptAcquireContextW(&prov, nullptr, nullptr, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) return false;
    if (CryptCreateHash(prov, CALG_SHA_256, 0, 0, &hash)) {
        DWORD len = 32;
        ok = CryptHashData(hash, (const BYTE*)in.data(), (DWORD)in.size(), 0) &&
             CryptGetHashParam(hash, HP_HASHVAL, out, &len, 0) && len == 32;
        CryptDestroyHash(hash);
    }
    CryptReleaseContext(prov, 0);
    return ok;
}

// A fresh nonce per request, covered by the signature, so a captured
// "licensed" answer can't be replayed later or on another machine.
std::string RandomNonce() {
    BYTE buf[16] = {};
    if (!BCRYPT_SUCCESS(BCryptGenRandom(nullptr, buf, sizeof(buf), BCRYPT_USE_SYSTEM_PREFERRED_RNG)))
        return "";
    char hex[33];
    for (int i = 0; i < 16; i++) snprintf(hex + i * 2, 3, "%02x", buf[i]);
    return std::string(hex, 32);
}

// Verifies an ECDSA P-256 signature (raw r||s) over SHA-256 of `message`,
// against the compiled-in public key.
bool VerifySignature(const std::string& message, const std::string& sigHex) {
    std::vector<BYTE> pub = FromHex(kServerPublicKey);
    std::vector<BYTE> sig = FromHex(sigHex);
    if (pub.size() != 64 || sig.size() != 64) return false;

    BYTE digest[32];
    if (!Sha256Raw(message, digest)) return false;

    // BCRYPT_ECCKEY_BLOB: header, then X, then Y.
    std::vector<BYTE> blob(sizeof(BCRYPT_ECCKEY_BLOB) + 64);
    auto* hdr = reinterpret_cast<BCRYPT_ECCKEY_BLOB*>(blob.data());
    hdr->dwMagic = BCRYPT_ECDSA_PUBLIC_P256_MAGIC;
    hdr->cbKey = 32;
    memcpy(blob.data() + sizeof(BCRYPT_ECCKEY_BLOB), pub.data(), 64);

    BCRYPT_ALG_HANDLE alg = nullptr;
    BCRYPT_KEY_HANDLE key = nullptr;
    bool ok = false;

    if (BCRYPT_SUCCESS(BCryptOpenAlgorithmProvider(&alg, BCRYPT_ECDSA_P256_ALGORITHM, nullptr, 0))) {
        if (BCRYPT_SUCCESS(BCryptImportKeyPair(alg, nullptr, BCRYPT_ECCPUBLIC_BLOB, &key,
                                                blob.data(), (ULONG)blob.size(), 0))) {
            ok = BCRYPT_SUCCESS(BCryptVerifySignature(key, nullptr, digest, 32,
                                                       sig.data(), (ULONG)sig.size(), 0));
            BCryptDestroyKey(key);
        }
        BCryptCloseAlgorithmProvider(alg, 0);
    }
    return ok;
}

// ---- tiny JSON helpers --------------------------------------------------

// The server's replies are flat and machine-generated, so a full JSON
// parser would be overkill. These just look for the one field we care about.
bool JsonBoolTrue(const std::string& body, const char* field) {
    std::string needle = std::string("\"") + field + "\"";
    size_t p = body.find(needle);
    if (p == std::string::npos) return false;
    p = body.find(':', p + needle.size());
    if (p == std::string::npos) return false;
    p = body.find_first_not_of(" \t", p + 1);
    if (p == std::string::npos) return false;
    return body.compare(p, 4, "true") == 0;
}

std::string JsonString(const std::string& body, const char* field) {
    std::string needle = std::string("\"") + field + "\"";
    size_t p = body.find(needle);
    if (p == std::string::npos) return "";
    p = body.find(':', p + needle.size());
    if (p == std::string::npos) return "";
    size_t q = body.find('"', p);
    if (q == std::string::npos) return "";
    size_t e = body.find('"', q + 1);
    if (e == std::string::npos) return "";
    return body.substr(q + 1, e - q - 1);
}

// ---- HTTP ---------------------------------------------------------------

struct Response {
    bool sent = false; // false = couldn't reach the server at all
    DWORD status = 0;
    std::string body;
};

// One-shot WinHTTP request. `path` must already start with '/'.
Response Request(const wchar_t* verb, const std::string& path, const std::string& body) {
    Response out;

    std::wstring url = Widen(ServerURL());
    URL_COMPONENTS uc = {};
    uc.dwStructSize = sizeof(uc);
    wchar_t host[256] = {};
    uc.lpszHostName = host;
    uc.dwHostNameLength = _countof(host);
    if (!WinHttpCrackUrl(url.c_str(), (DWORD)url.size(), 0, &uc)) {
        Log("license: configured server URL is not valid");
        return out;
    }
    bool https = uc.nScheme == INTERNET_SCHEME_HTTPS;

    HINTERNET session = WinHttpOpen(L"netvis", WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,
                                    WINHTTP_NO_PROXY_NAME, WINHTTP_NO_PROXY_BYPASS, 0);
    if (!session) return out;

    // Don't let a hung server hold up app startup.
    WinHttpSetTimeouts(session, 4000, 4000, 6000, 6000);

    HINTERNET conn = WinHttpConnect(session, host, uc.nPort, 0);
    if (!conn) {
        WinHttpCloseHandle(session);
        return out;
    }

    std::wstring wpath = Widen(path);
    HINTERNET req = WinHttpOpenRequest(conn, verb, wpath.c_str(), nullptr, WINHTTP_NO_REFERER,
                                       WINHTTP_DEFAULT_ACCEPT_TYPES, https ? WINHTTP_FLAG_SECURE : 0);
    if (!req) {
        WinHttpCloseHandle(conn);
        WinHttpCloseHandle(session);
        return out;
    }

    const wchar_t* headers = body.empty() ? WINHTTP_NO_ADDITIONAL_HEADERS
                                          : L"Content-Type: application/json\r\n";
    BOOL ok = WinHttpSendRequest(req, headers, (DWORD)-1,
                                 body.empty() ? WINHTTP_NO_REQUEST_DATA : (LPVOID)body.data(),
                                 (DWORD)body.size(), (DWORD)body.size(), 0);
    if (ok) ok = WinHttpReceiveResponse(req, nullptr);

    if (ok) {
        out.sent = true;
        DWORD size = sizeof(out.status);
        WinHttpQueryHeaders(req, WINHTTP_QUERY_STATUS_CODE | WINHTTP_QUERY_FLAG_NUMBER,
                            WINHTTP_HEADER_NAME_BY_INDEX, &out.status, &size, WINHTTP_NO_HEADER_INDEX);

        DWORD avail = 0;
        while (WinHttpQueryDataAvailable(req, &avail) && avail > 0) {
            std::string chunk(avail, '\0');
            DWORD read = 0;
            if (!WinHttpReadData(req, chunk.data(), avail, &read)) break;
            out.body.append(chunk, 0, read);
            if (out.body.size() > 64 * 1024) break; // the server never sends anything this big
        }
    } else {
        Log("license: request failed, GetLastError=%lu", (unsigned long)GetLastError());
    }

    WinHttpCloseHandle(req);
    WinHttpCloseHandle(conn);
    WinHttpCloseHandle(session);
    return out;
}

} // namespace

// ---- public -------------------------------------------------------------

const std::string& HWID() {
    static const std::string id = [] {
        std::string raw = MachineGuid() + "|" + SystemVolumeSerial();
        std::string h = HashHex(raw);
        if (h.empty()) h = "unknown"; // hashing can only fail if CryptoAPI is broken
        Log("license: hwid computed");
        return h;
    }();
    return id;
}

const std::string& ServerURL() {
    static const std::string url = kServer;
    return url;
}

namespace {
std::atomic<int> g_lastDaysLeft{-1};
std::atomic<bool> g_lastWasTrial{false};

// Pulls an integer field out of a flat JSON object, or -1 if absent.
int JsonInt(const std::string& body, const char* field) {
    std::string needle = std::string("\"") + field + "\"";
    size_t p = body.find(needle);
    if (p == std::string::npos) return -1;
    p = body.find(':', p + needle.size());
    if (p == std::string::npos) return -1;
    p = body.find_first_not_of(" \t", p + 1);
    if (p == std::string::npos || !isdigit((unsigned char)body[p])) return -1;
    return atoi(body.c_str() + p);
}
} // namespace

int LastDaysLeft() { return g_lastDaysLeft.load(); }
bool LastWasTrial() { return g_lastWasTrial.load(); }

Result AuthenticateEx() {
    Result out;
    std::string nonce = RandomNonce();
    if (nonce.empty()) {
        // No randomness means no replay protection, so refuse rather than
        // fall back to an unprotected check.
        Log("license: could not generate a nonce");
        out.status = Status::Unreachable;
        return out;
    }

    Response r = Request(L"GET", "/authentificate/" + HWID() + "?n=" + nonce, "");
    if (!r.sent) {
        Log("license: server unreachable");
        out.status = Status::Unreachable;
        return out;
    }
    if (r.status == 200 && JsonBoolTrue(r.body, "ok")) {
        // A "yes" is only believed if it's signed by the real server. This
        // is the check that survives a redirected hostname, a rogue root
        // certificate, or a proxy in the middle - none of which can produce
        // a signature matching the key compiled in above.
        std::string expiresAt = JsonString(r.body, "expires_at");
        std::string echoed = JsonString(r.body, "nonce");
        std::string sig = JsonString(r.body, "sig");
        std::string message = "netvis-auth-v1|" + HWID() + "|" + expiresAt + "|" + nonce;

        if (echoed != nonce) {
            // Either a replayed answer or a server that ignored our nonce.
            Log("license: nonce mismatch - rejecting");
            out.status = Status::NotLicensed;
            return out;
        }
        if (!VerifySignature(message, sig)) {
            Log("license: signature check failed - rejecting");
            out.status = Status::NotLicensed;
            return out;
        }

        out.status = Status::Licensed;
        out.daysLeft = JsonInt(r.body, "days_left");
        out.trial = JsonBoolTrue(r.body, "trial");
        g_lastDaysLeft.store(out.daysLeft);
        g_lastWasTrial.store(out.trial);
        Log("license: machine is licensed (%s, %d days left)", out.trial ? "trial" : "paid",
            out.daysLeft);
        return out;
    }
    // The server distinguishes "ran out" from "never activated" so the user
    // gets told to renew rather than being asked for a key they already own.
    if (JsonString(r.body, "error") == "expired") {
        out.trial = JsonBoolTrue(r.body, "trial");
        g_lastDaysLeft.store(0);
        g_lastWasTrial.store(out.trial);
        Log("license: %s expired", out.trial ? "trial" : "license");
        out.status = Status::Expired;
        return out;
    }
    Log("license: not licensed (http %lu)", (unsigned long)r.status);
    out.status = Status::NotLicensed;
    return out;
}

Status Authenticate() { return AuthenticateEx().status; }

std::string Normalize(const std::string& raw) {
    std::string out;
    out.reserve(raw.size());
    for (unsigned char c : raw) {
        char u = (char)toupper(c);
        // Letters, digits, dash and underscore are key material; spaces and
        // line breaks from a paste are not. Dashes matter here - Polar's
        // keys are NETVIS_1C285B2D-6CE6-..., and stripping them would turn
        // a valid key into a rejected one.
        if ((u >= 'A' && u <= 'Z') || (u >= '0' && u <= '9') || u == '-' || u == '_') out += u;
    }
    return out;
}

bool PlausibleKey(const std::string& normalized) {
    return (int)normalized.size() >= kKeyMinLength && (int)normalized.size() <= kKeyMaxLength;
}

bool StartTrial(std::string* error) {
    Response r = Request(L"POST", "/trial/" + HWID(), "{\"os\":\"windows\"}");
    if (!r.sent) {
        if (error) *error = "Couldn't reach the license server. Check your internet connection.";
        return false;
    }
    if (r.status == 200 && JsonBoolTrue(r.body, "ok")) {
        // Same rule as activation: don't believe this reply on its own.
        // The signed check is what actually decides, so a fake server
        // can't hand out trials any more than it can hand out licenses.
        if (AuthenticateEx().status != Status::Licensed) {
            if (error) *error = "The trial started but didn't verify. Please try again.";
            Log("license: trial not confirmed by the signed check");
            return false;
        }
        Log("license: trial started");
        return true;
    }
    std::string serverMsg = JsonString(r.body, "error");
    if (error) *error = serverMsg.empty() ? "Could not start the trial." : serverMsg;
    Log("license: trial refused (http %lu)", (unsigned long)r.status);
    return false;
}

bool Activate(const std::string& rawKey, std::string* error) {
    // Normalise here too, not just in the UI, so any other caller gets the
    // same forgiving behaviour.
    std::string key = Normalize(rawKey);
    if (!PlausibleKey(key)) {
        if (error) *error = "That doesn't look like a license key.";
        return false;
    }

    std::string body = "{\"hwid\":\"" + HWID() + "\",\"os\":\"windows\"}";
    Response r = Request(L"POST", "/validate/" + key, body);

    if (!r.sent) {
        if (error) *error = "Couldn't reach the licensing server. Check your internet connection.";
        return false;
    }
    if (r.status == 200 && JsonBoolTrue(r.body, "ok")) {
        // Don't take /validate's word for it: confirm through the signed
        // endpoint. Otherwise a fake server could wave the user past
        // activation without ever producing a valid signature.
        // Re-reading through the signed check does two jobs: it proves a
        // real server issued the license, and it refreshes the cached
        // trial flag and day count. Without that refresh the UI would keep
        // showing a trial countdown for a machine that has just been paid
        // for, until something else happened to re-check.
        Result confirmed = AuthenticateEx();
        if (confirmed.status != Status::Licensed) {
            if (error) *error = "The server confirmed the key but the license didn't verify.";
            Log("license: activation not confirmed by the signed check");
            return false;
        }
        Log("license: activated this machine (trial=%d, %d days)", (int)confirmed.trial,
            confirmed.daysLeft);
        return true;
    }
    std::string serverMsg = JsonString(r.body, "error");
    if (error) *error = serverMsg.empty() ? "The server rejected that license key." : serverMsg;
    Log("license: activation failed (http %lu): %s", (unsigned long)r.status, error ? error->c_str() : "");
    return false;
}

} // namespace license
