// Licensing client: asks the netvis licensing server whether this machine
// is allowed to run, and redeems a license key if it isn't.
//
// Two calls, mirroring the server's two endpoints:
//   Authenticate()  GET  /authentificate/<hwid>
//   Activate(key)   POST /validate/<key>   body {"hwid":..,"os":"windows"}
#pragma once
#include <string>

namespace license {

// Stable per-machine fingerprint: the Windows MachineGuid plus the system
// volume serial, hashed. Survives reboots and app reinstalls; changes if
// the OS is reinstalled, which is the behaviour you want from a HWID.
const std::string& HWID();

// The licensing server, compiled into the binary and not overridable at
// runtime - a config file holding this would let anyone redirect netvis at
// a server that approves everything.
const std::string& ServerURL();
extern const char* const kServer;

enum class Status {
    Licensed,     // server says this machine may run
    NotLicensed,  // server answered, but this machine isn't activated (or is revoked)
    Expired,      // was licensed, term ran out - different message, same gate
    Unreachable,  // couldn't reach the server at all
};

struct Result {
    Status status = Status::Unreachable;
    int daysLeft = -1; // -1 = unknown or no expiry
    bool trial = false;
};

// GET /authentificate/<hwid>
Status Authenticate();
Result AuthenticateEx();

// Days remaining on this machine's license as of the last check, or -1.
int LastDaysLeft();

// Whether that license is the free trial rather than a paid one.
bool LastWasTrial();

// POST /trial/<hwid>. Starts the one free trial this machine gets. The
// server decides and records it, so there is nothing locally to reset -
// and the trial's expiry arrives through the same signed check as a paid
// license, so it can't be extended from this side either.
bool StartTrial(std::string* error);

// POST /validate/<key>. On failure `error` gets a message suitable for
// showing the user.
bool Activate(const std::string& key, std::string* error);

// Keys come in two shapes: the 30-character ones generated by the
// licensing tool, and the longer NETVIS_<uuid> ones Polar issues to
// customers. Rather than encode either format here - which would mean a
// client update every time the shop changes - the client only checks the
// length is plausible and lets the server decide.
constexpr int kKeyMinLength = 20;
constexpr int kKeyMaxLength = 100;

// Upper-cases and drops whitespace, so a key pasted out of an email with
// line breaks in it still works. Dashes and underscores are kept, because
// Polar's keys contain them.
std::string Normalize(const std::string& raw);

// Whether this looks like a key worth sending to the server.
bool PlausibleKey(const std::string& normalized);

} // namespace license
